name: build test deploy api1

on:  
  push:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: api1-1002
  AZURE_WEBAPI1_PACKAGE_PATH: '.'

jobs:
  build-test-deploy:
    
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    
    - name: Restore dependencies
      run: dotnet restore AspnetWebapiAzure.sln
    
    - name: Build
      run: dotnet build AspnetWebapiAzure.sln --configuration Release --no-restore
    
    - name: Test
      run: dotnet test AspnetWebapiAzure.sln --verbosity normal --configuration Release

    - name: Publish
      run: dotnet publish src\AspnetWebapiAzureDeploy.Api1\AspnetWebapiAzureDeploy.Api1.csproj --configuration Release -o '${{ env.AZURE_WEBAPI1_PACKAGE_PATH }}/api1'

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPI1_PACKAGE_PATH }}/api1