name: build test deploy

on:  
  push:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: api1-1002
  AZURE_WEBAPI1_PACKAGE_PATH: '.'

jobs:
  build-test-deploy:
    
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    
    - name: Restore dependencies
      run: dotnet restore AspnetWebapiAzureDeploy.sln
    
    - name: Build
      run: dotnet build AspnetWebapiAzureDeploy.sln --configuration Release --no-restore
    
    - name: Test
      run: dotnet test AspnetWebapiAzureDeploy.sln --verbosity normal --configuration Release

    - name: Publish api1
      run: dotnet publish src\AspnetWebapiAzureDeploy.Api1\AspnetWebapiAzureDeploy.Api1.csproj --configuration Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/api1'

    - name: Publish api2
      run: dotnet publish src\AspnetWebapiAzureDeploy.Api2\AspnetWebapiAzureDeploy.Api2.csproj --configuration Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/api2'

    - name: Publish webapp
      run: dotnet publish src\AspnetWebapiAzureDeploy.WebApp\AspnetWebapiAzureDeploy.WebApp.csproj --configuration Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/webapp'