name: build test deploy

on:  
  push:
    branches: [ main ]

env:
  AZURE_API1_NAME: aspnet-webapi-azure-deploy-api11002
  AZURE_API2_NAME: aspnet-webapi-azure-deploy-api11002
  AZURE_WEBAPP_NAME: aspnet-webapi-azure-deploy-webapp1002
  PUBLISH_PATH: '/publish'

jobs:
  build-test-deploy:
    
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    
    - name: Restore dependencies
      run: dotnet restore AspnetWebapiAzureDeploy.sln
    
    - name: Build
      run: dotnet build AspnetWebapiAzureDeploy.sln --configuration Release --no-restore
    
    - name: Test
      run: dotnet test AspnetWebapiAzureDeploy.sln --verbosity normal --configuration Release

    - name: Publish api1
      run: dotnet publish src\AspnetWebapiAzureDeploy.Api1\AspnetWebapiAzureDeploy.Api1.csproj --configuration Release -o '${{ env.PUBLISH_PATH }}/api1'

    - name: Publish api2
      run: dotnet publish src\AspnetWebapiAzureDeploy.Api2\AspnetWebapiAzureDeploy.Api2.csproj --configuration Release -o '${{ env.PUBLISH_PATH }}/api2'

    - name: Publish webapp
      run: dotnet publish src\AspnetWebapiAzureDeploy.WebApp\AspnetWebapiAzureDeploy.WebApp.csproj --configuration Release -o '${{ env.PUBLISH_PATH }}/webapp'

    - name: 'Deploy to Azure api1'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_API1_NAME }}
        publish-profile: ${{ secrets.AZURE_API1_PUBLISH_PROFILE }}
        package: '${{ env.PUBLISH_PATH }}/api1'

    - name: 'Deploy to Azure api2'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_API2_NAME }}
        publish-profile: ${{ secrets.AZURE_API2_PUBLISH_PROFILE }}
        package: '${{ env.PUBLISH_PATH }}/api2'

    - name: 'Deploy to Azure webapp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '${{ env.PUBLISH_PATH }}/webapp'