name: build test deploy

on:  
  push:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: api1-1002
  AZURE_WEBAPI1_PACKAGE_PATH: '.'

jobs:
  build-test-deploy:
    
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    
    - name: Restore dependencies
      run: dotnet restore AspnetWebapiAzureDeploy.sln
    
    - name: Build
      run: dotnet build AspnetWebapiAzureDeploy.sln --configuration Release --no-restore
    
    - name: Test
      run: dotnet test AspnetWebapiAzureDeploy.sln --verbosity normal --configuration Release

    